# Generated by Django 3.2.16 on 2024-02-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240202_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
