# Generated by Django 3.2.16 on 2024-02-08 12:02

import birthday.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_alter_birthday_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(validators=[birthday.validators.real_age], verbose_name='Дата рождения'),
        ),
    ]
